### ISSUE TITLE
Service not starting on tumux

### ISSUE THREAD

**Issue by counterfitninja** [TapeWerm/MCscripts#1]
I have got an Azure Ubuntu and grabbed Bedrock server. Found your scripts to allow cron backups. However when I try to start the bedrock server via the dethatched tmux it wont start. I think its because the tmux sessions is starting in a random directory so the bedrock server command D_LIBRARY_PATH=. ./bedrock_server  fails.   any ideas? the output log is below. 

mcbe@MCBE.service - Minecraft Bedrock Edition server
   Loaded: loaded (/etc/systemd/system/mcbe@.service; indirect; vendor preset: enabled)
   Active: failed (Result: exit-code) since Mon 2019-01-21 20:49:59 UTC; 40min ago
  Process: 1466 ExecStop=/opt/MC/MCstop.sh MCBE /tmp/MCBE (code=exited, status=2)
  Process: 1021 ExecStart=/usr/bin/tmux -S /tmp/MCBE new -ds MCBE LD_LIBRARY_PATH=. ./bedrock_server (code=exited, s
 Main PID: 1043 (code=exited, status=0/SUCCESS)

Jan 21 20:49:52 bedrock-ubt systemd[1]: Starting Minecraft Bedrock Edition server...
Jan 21 20:49:53 bedrock-ubt systemd[1]: Started Minecraft Bedrock Edition server.
Jan 21 20:49:59 bedrock-ubt MCstop.sh[1466]: no server running on /tmp/MCBE
Jan 21 20:49:59 bedrock-ubt MCstop.sh[1466]: No session MCBE on socket /tmp/MCBE
Jan 21 20:49:59 bedrock-ubt systemd[1]: mcbe@MCBE.service: Control process exited, code=exited status=2
Jan 21 20:49:59 bedrock-ubt systemd[1]: mcbe@MCBE.service: Failed with result 'exit-code'.

**Comment by TapeWerm** [comment]
The systemd unit file makes a socket for tmux in /tmp named after the instance. MCstop.sh outputs "No session %i on socket /tmp/%i". MCBEbackup.sh also outputs the same error when it can't find a tmux session named %i on socket /tmp/%i . MCstop.sh expects 1-2 positional parameters: $sessionname and optionally the 2nd, $tmux_socket . What's weird is ExecStart says exited, it looks truncated but I'm gonna assume it was status 0. I'm gonna log into my server and see what happens when I delete the socket after stopping the service and start it again.

**Comment by TapeWerm** [comment]
It worked fine on my end, and when I made a tmux session as a different user on that socket I got a permissions error. Was ExecStart's exit status 0? That would be the output I'd expect for MCstop.sh if ExecStart failed as there would indeed be no server. Try running `tmux -S /tmp/MCBE new -ds MCBE 'LD_LIBRARY_PATH=. ./bedrock_server'` by hand as user mc.
Edit: I forgot single quotes that got eaten by the output, they're kinda necessary.

**Comment by TapeWerm** [comment]
I should probably add to the README but MCBEbackup.sh can be added to your cron without a systemd service. The parameters it expects are $server_dir $sessionname [$backup_dir] [$tmux_socket]. If you don't use the service and don't run more than one server on the same host you can use the default tmux socket, making the tmux -S flag and ./MCBEbackup.sh $tmux_socket parameter unnecessary.

**Comment by counterfitninja** [comment]
Thanks, ill try a few things today and have a play around. In theory it should all work

**Comment by TapeWerm** [comment]
I forgot to add quotes in `tmux -S /tmp/MCBE new -ds MCBE 'LD_LIBRARY_PATH=. ./bedrock_server'`
I copied from the output you pasted here, and the quotes got eaten. Many minutes were lost in confusion until I realized tmux tried to set the environment variable as a command until I put the single quotes around both the set and running of the bedrock server.
Edit: The quotes are already in the systemd unit file.
Edit: Electric Boogaloo: Fix quotes

**Comment by counterfitninja** [comment]
just tried as MC and getting this now. 

mc@bedrock-ubt:/tmp$ tmux -S /tmp/MCBE new -ds 'MCBE LD_LIBRARY_PATH=. ./bedrock_server'
bad session name: MCBE LD_LIBRARY_PATH=. ./bedrock_server
mc@bedrock-ubt:/tmp$ ls
MCBE
mc@bedrock-ubt:/tmp$

**Comment by TapeWerm** [comment]
Ah, my bad. Quotes are put in wrong place. `tmux -S /tmp/MCBE new -ds MCBE 'LD_LIBRARY_PATH=. ./bedrock_server'` Also, forgot to mention that dir the unit file starts in is /opt/MC/%i where %i is the instance name, which seems to be MCBE.

**Comment by counterfitninja** [comment]
ha ha.. sorry only just looked at this and noticed the quote was missing. It runs without error, but without creating the tmux. ill play later and keep you posted.

**Comment by TapeWerm** [comment]
By runs without error, do you mean the service is active but you can't find the tmux session? Cause the unit file user is mc so you'd have to `su mc` and `tmux -S /tmp/MCBE ls` or whatever the instance is to see it. Then you'd `tmux -S /tmp/MCBE a` to attach. It's a pain but it's nice to run the server as a different user that shouldn't be root.

**Comment by counterfitninja** [comment]
Ok call me an idiot. The issue was that when i imported my world i had unzipped it as root, so when MC ran the bedrock command it was failing.  changed all permissions in the worlds folder to MC and its works fine. Sorry for being dim and thanks for your help.

**Comment by TapeWerm** [comment]
It happens, same way I derp'd my quote. If you look at my commit history you'll realize I'm little better. Thanks to you I realized I didn't say how to attach to the tmux session in the README. Things like that are tacit to me but I forget it's obscure to anyone else.
