### ISSUE TITLE
Example request for the MCBEbackup.sh script

### ISSUE THREAD

**Issue by lurk24** [TapeWerm/MCscripts#11]
I was hoping to get an example of how to use the MCBEbackup script... 

I am running on Ubuntu and I followed the instructions from the readme for Setup and Bedrock Edition Setup (i skipped Java edition setup). It seems like the bedrock_server is running but i am unable to figure out the correct syntax for the MCBEbackup.sh script - can you provide a simple example?

**Comment by TapeWerm** [comment]
If you're using the mcbe@.service just do `sudo systemctl start mcbe-backup@MCBE` and that will pass the needed arguments for you. If you're not using the bedrock server systemd service, you need to start bedrock server in a tmux session. To make a tmux session running bedrock server, run `tmux new -ds MCBE 'LD_LIBRARY_PATH=. ./bedrock_server` Then run `./MCBEbackup.sh (insert server directory here) MCBE` to backup the bedrock server in server directory in tmux session MCBE. tmux lets me send-keys and read the output of it, which is needed for the backup command in bedrock server.

**Comment by TapeWerm** [comment]
Reluctantly I add to the README. I don't want to explain systemd too much, but I concede manual backups are too useful to leave out. systemd can be a rabbithole but considering some of these services will be run manually there is now a basic howto in https://github.com/TapeWerm/MCscripts#notes
