### ISSUE TITLE
Backups created by this lack changes

### ISSUE THREAD

**Issue by ZarielZariel** [TapeWerm/MCscripts#12]
They are of the correct size and show the correct name, but upon putting them into the singleplayer worlds directory, the world is vanilla of that seed - unchanged.

**Comment by TapeWerm** [comment]
Strange, I haven't played Minecraft Bedrock lately as I've been doing homework and fixing computers, but I'll check to see if a recent update to the game broke the `save hold` command.

**Comment by TapeWerm** [comment]
On a single test the backup succeeded in preserving changes made before `save hold` was ran. This is bedrock you're talking about right? Is this consistent? It's possible my one test is just one roll of the dice.

**Comment by TapeWerm** [comment]
I should also note if you put backups in singleplayer you lose your inventory. I believe this holds true across Bedrock and Java Minecraft. Are the blocks different?

**Comment by ZarielZariel** [comment]
The blocks are different, unfortunately.

**Comment by ZarielZariel** [comment]
It's fine though, I just switched to my old give warning -> stop server ->
backup -> restart server script. Less elegant but it works and losing data is obviously a dealbreaker.

It's very possible that I'm doing something wrong, but it's not immediately apparent what it could be given that the backup goes off and clearly it's of the appropriate world.

**Comment by TapeWerm** [comment]
I don't think you're doing anything wrong, losing your inventory in singleplayer is standard behavior for bedrock server. I didn't even know you could see your inventory in copied worlds from when the server is off in singeplayer.

**Comment by TapeWerm** [comment]
I still don't see my inventory in singleplayer when I copy the world when the server is off. Regardless I'm going to close this issue as the world behaves as expected in multiplayer.

**Comment by ZarielZariel** [comment]
No, I'm referring to the *blocks* being different.

**Comment by ZarielZariel** [comment]
Not my inventory. The entire world is as the seed generates it from day 1 -
with no buildings, changes, etc.

**Comment by TapeWerm** [comment]
Oh, not different from before the backup, but different from the changes. I'm not sure why that is happening.

**Comment by TapeWerm** [comment]
What do you see in the server console? You should see a list of files after `server query`. What happens if you copy the world after typing `save hold`? Remember to enter `save resume` after you copy the world. The script copies the files listed and truncates by the bytes listed after. Ex: $file:$bytes

**Comment by ZarielZariel** [comment]
I am afraid that I have since reinstalled the server - which I recognize is entirely unhelpful and gives you zero assistance in replicating the problem. However, I figured that if I were in your shoes, I'd still prefer to hear about it so it was floating in the back of my mind if others have similar experiences than to hear nothing.

**Comment by TapeWerm** [comment]
Thank you. I'm not sure if it was the script or the server's `save` command's fault, but this is good to know should it happen again.
