### ISSUE TITLE
Discord webhooks setup

### ISSUE THREAD

**Issue by ghost** [TapeWerm/MCscripts#17]
So, I'm not really understanding what am I supposed to do in the instruction of `open nano <that file webhooks.txt>` and fill this in.
Do I need to copy that text and put it on there or I'm supposed to fill with my own info?

**Comment by ghost** [comment]
I figured it out by myself, I put the Discord webhook url but still this doesn't work for me:( It doesn't post any message in the channel

**Comment by TapeWerm** [comment]
That file has one webhook URL per line. What do `systemctl status mcbe-log@MCBE` and `journalctl -eu mcbe-log@MCBE` say? `journalctl -fu mcbe-log@MCBE` tails the output so you can join the server and see the error as it happens.

**Comment by ghost** [comment]
It was a matter of time, some mins ago when my friend joined the server it printed it out in the Discord chat. Thanks anyways
