### ISSUE TITLE
Centralized configuration

### ISSUE THREAD

**Issue by jared-hess** [TapeWerm/MCscripts#26]
Any thoughts on adding a centralized configuration file of some type? 
Specifically we give the users 60s warning before the server stops, so I edited the mcbe unit file to pass the '-s' parameter to the stop script. This works great, but it's easy to accidentally overwrite the modified file when updating. 
Or maybe there is a better way to make this configurable in systemd?

**Comment by TapeWerm** [comment]
You could make a bash script that sed's the file, or I could make a config. I've thought of it, a config would be more reliable, if I changed the unit file a sed expression could break. In systemd the only argument a service gets is its instance name, if applicable. I don't know a better way.

**Comment by TapeWerm** [comment]
I'm going minimal effort. Making configuration files makes setup longer, I just show how to use sed. It's not something I'd usually recommend, but it's optional and this isn't a user-friendly tool anyways.
