### ISSUE TITLE
Scheduled restart

### ISSUE THREAD

**Issue by jared-hess** [TapeWerm/MCscripts#28]
Any thoughts on adding the ability to schedule a server restart once a day or so?
I think it would just involve a timer that activates a one shot service that runs "systemctl restart mcbe@foobar", to ensure that the service restarts cleanly.

**Comment by TapeWerm** [comment]
I could suggest making a root crontab that restarts mcbe@foobar daily. A timer for such a trivial task seems overkill. It should make sure the service is active first (`systemctl is-active --quiet mcbe@foobar && systemctl restart mcbe@foobar`).
Edit: Added quiet flag.

**Comment by TapeWerm** [comment]
Been a while coming but I finally got to this.
