### ISSUE TITLE
Dependency failed for Automatically remove Minecraft Bedrock Edition server world backups more than 2-weeks-old @ MCBE.

### ISSUE THREAD

**Issue by flplv** [TapeWerm/MCscripts#30]
This line:

https://github.com/TapeWerm/MCscripts/blob/2b2049cef9ace7301241c7001e6ce91fbcec30ce/systemd/mc-rmbackup%40.service#L4

Fails, because the backup service is no longer running when this one starts. It is programmed to start after. Maybe you wanted to depend on the timer instead of the service?

**Comment by TapeWerm** [comment]
The requisite on mcbe-getzip worked when it exited successfully, but not when it failed. I don't actually use rmbackup, so it rarely gets tested. I have removed all requisites on oneshot services, and will push soon.

**Comment by flplv** [comment]
Thank you my friend
