### ISSUE TITLE
Need to use dos2unix on server.properties from Windows server

### ISSUE THREAD

**Issue by Ginko72** [TapeWerm/MCscripts#33]
You might add a note to the readme that folks moving servers from Windows to Ubuntu need to scrub the server.properties file of the ^M characters.  dos2unix does this quickly and easily.

Without conversion, the backups fail because the ^M fouls the bit of the script testing for the existence of the world directory.

Thanks for the awesome tool!

Cheers,
Tim

**Comment by TapeWerm** [comment]
I skipped dos2unix as it's one more package to download and used sed to achieve the same.

**Comment by Ginko72** [comment]
I see, I was using it wrong.   I created an empty server and copied in my files rather than using the script that would have fixed it for me.

Cheers,
Tim

**Comment by TapeWerm** [comment]
I didn't add the sed to imitate dos2unix until after you made this issue.

**Comment by Ginko72** [comment]
I wonder if a note about converting your windows server is needed in the main Readme.  At a minimum, a mention that you can simply copy the server directory and then run  MCBE update on it.  Not sure.  As you have said before, this is not intended to be user friendly.  ;)

Unrelated, thanks for providing this tool.  It has really improved my server set up.  I especially like the fact that making them services will automatically restart them if they crash.

**Comment by TapeWerm** [comment]
Derp, MCBEautoUpdate will not be happy if the server service fails to start cause of the EXE. I'll fix.
