### ISSUE TITLE
After updating, discord webhook prints xuid's rather than usernames

### ISSUE THREAD

**Issue by jared-hess** [TapeWerm/MCscripts#36]
MCBE 1.16.100 was released today, after updating we are getting the xuid values in our discord channel from the webhook rather than usernames. Seems maybe they changed the order in which they are printed?

When I log in, this is the current format from the server console:
`[INFO] Player connected: <player name>, xuid: <xuid value>`

**Comment by TapeWerm** [comment]
Heh, they removed the timestamp from the header which broke `cut -d ' '`. It's been replaced with regex which should be more resilient to these types of changes.
Edit: Tested kick too with `Nov 17 17:17:47 glados bash[1539]: Kicked Vincent294 from the game: ' I don't need a reason around these parts scoundrel'` and it worked, player and reason.

**Comment by jared-hess** [comment]
Awesome, thanks for the quick fix!

**Comment by TapeWerm** [comment]
lol I looked back at your code contribution in June and your sed is almost identical to what I wrote today. I wanted to avoid regex cause it's confusing for anyone who doesn't know it but I wound up back where you started. I shouldn't have changed it. :p
