### ISSUE TITLE
mcbe-getzip service fails to start with dependency failure

### ISSUE THREAD

**Issue by jared-hess** [TapeWerm/MCscripts#37]
On our server, even though it has internet access the 'network-online.target' service does not automatically start, which causes the 'getzip' oneshot to fail...
```
Nov 17 14:10:49 myhost.domain.com systemd[1]: Network is Online is not active.
Nov 17 14:10:49 myhost.domain.com systemd[1]: Dependency failed for Automatically download Minecraft Bedrock Edition server ZIP.
-- Subject: Unit mcbe-getzip.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- Unit mcbe-getzip.service has failed.
--
-- The result is RESULT.
Nov 17 14:10:49 myhost.domain.com systemd[1]: mcbe-getzip.service: Job mcbe-getzip.service/start failed with result 'dependency'.
```
I worked around this momentarily by simply starting the 'network-online.target' service manually. I think another workaround would be to enable 'systemd-networkd-wait-online.service' which would delay the boot process until the network was detected to be online, but I haven't tried this.

From my understanding, by default 'network-online.target' won't be pulled in unless it is required by another unit. Since the getzip unit uses 'Requisite=' instead of 'Requires=', getzip fails rather than trying to actually start 'network-online.target'. From [the docs](https://www.freedesktop.org/wiki/Software/systemd/NetworkTarget/):

> Note that normally, if no service requires it, and if no remote mount point is configured this target is not pulled into the boot, thus avoiding any delays during boot should the network not be available.

I _believe_ the preferred way to do this would simply be to use 'Requires=' rather than 'Requisite=', but I could be wrong.

**Comment by TapeWerm** [comment]
I'll read into networkd-wait-online tomorrow. Or maybe tonight cause I have no love for my sleep schedule and had too much caffeine today.

**Comment by TapeWerm** [comment]
I just removed the Requisite, the ExecStartPre is the host command to test DNS anyways.

**Comment by jared-hess** [comment]
Many thanks Vincent :)
