### ISSUE TITLE
Incorrect permissions on bedrock_server file after most recent BDS update

### ISSUE THREAD

**Issue by jared-hess** [TapeWerm/MCscripts#38]
In the most recent download of BDS for linux, the "bedrock_server" file does not have execute permissions for some reason. This means after the autoupdate the server will fail to start without manual intervention to add the permission on the file (via chmod +x). 

```
Apr 06 11:18:19 myserver.com systemd[1]: Stopped Minecraft Bedrock Edition server @ MyServer.
Apr 06 11:18:19 myserver.com systemd[1]: Started Minecraft Bedrock Edition server @ Myserver.
Apr 06 11:18:19 myserver.com bash[6011]: /bin/bash: ./bedrock_server: Permission denied
```
My guess is it was just a mistake by Mojang when building the download. It might be best to set the permission as part of the update script to ensure the issue does not reoccur in the future.

**Comment by TapeWerm** [comment]
Working on it, good catch. I played Minecraft last week but have been busy doing homework this week so I didn't even notice.
