### ISSUE TITLE
mcbe-rmbackup tries to delete files in wrong directory

### ISSUE THREAD

**Issue by jared-hess** [TapeWerm/MCscripts#41]
Looks like mcbe-rmbackup service was never updated when the directory naming convention was switched from CamelCase to snake_case, it still points to "%i_Backups" instead of "%i_backups"

**Comment by TapeWerm** [comment]
Thank you, good catch. I need to remember to git grep for everything that could be affected by a rename, not just vim search in 1 file. When testing, this issue can only happen on case sensitive filesystems like ext4. From October 2017 to May 2021 I ran my Minecraft bedrock server on potato computers, dumping backups to USB drives and SD cards which use case insensitive filesystems like FAT32 or exFAT. When I tried to mv `Backups` to `backups` I had to use `backups1` as an intermediate filename cause `backups` resolved to `Backups` which already existed. Filesystems are a huge footgun, and until I learn automated testing I should grep more often.
