### ISSUE TITLE
Mention Pugmatt's BedrockConnect as a Nintendo Switch workaround

### ISSUE THREAD

**Issue by shaynemk** [TapeWerm/MCscripts#44]
https://github.com/TapeWerm/MCscripts/blob/5b0e69c3843758b58f4b745befe077193e69fb31/README.md?plain=1#L60

Aforementioned line says that you can't access a Bedrock dedicated server via Nintendo Switch, but I just found out you can by using Pugmatt's BedrockConnect (https://github.com/Pugmatt/BedrockConnect) project as essentially a serverlist/proxy. It utilizes DNS rewrites to redirect the built in featured servers to this piece of software, which is a serverlist you can use to then jump over to a custom server, i.e. a dedicated server (or potentially even a Java edition server...i've not tried this though, i've heard it can be hit or miss whether it works).

**Comment by TapeWerm** [comment]
I haven't tried phantom or this. I should at least try phantom, I link to it after all :p. I never tried the DNS solutions cause it's more crude than proxy.

**Comment by shaynemk** [comment]
Huh, I must have missed the reference to phantom...but I found the other project before these scripts anyways. Having nerdy nitpicky control over DNS as I do, it was rather easy to implement with my existing infrastructure. I'll have to give phantom a look.

**Comment by TapeWerm** [comment]
I came back to MCscripts to fix a bug, and I updated some broken links. I decided to not recommend any workarounds since I do not use them, but I think they're awesome. Sorry for mcbe_update failing to copy the whitelist in 1.18.10, the code has been refactored to avoid this in the future.
