### ISSUE TITLE
Autoupdate script updates server to incompatible version

### ISSUE THREAD

**Issue by jared-hess** [TapeWerm/MCscripts#45]
I'm not sure if this is an actual issue or more of a PSA, as I don't think anything can be done from our end. Mojang has started publishing 1.19 previews to the BDS download page instead of versions of the server that actually work with released versions of the client. This means the update (which will be picked up by the autoupdate script) will break playability for most players. From the [download page](https://www.minecraft.net/en-us/download/server/bedrock):

> From now until The Wild Update releases, this page will be serving up builds from the future! The Microsoft Build 2022 Conference will include a special demo that uses unreleased Minecraft features while connecting to a special Preview Dedicated Server (1.19.10). When The Wild Update releases, we will update the download page to offer a compatible Dedicated Server (1.19.0) which will still support the Build 2022 demo.
> **This does mean that we do not have a Dedicated Server that works with today's Minecraft release (1.18.33), and we apologize for this inconvenience.**

Based on this messaging, it seems like players using BDS are SOL until 1.19 drops unless they prevent updates on both the server and client, or opt into the beta/preview.

**Comment by TapeWerm** [comment]
Heh, thanks, I saw that last night. I thought about warning TheRemote too, but I don't know what any of us could've done last night. Once Mojang pushed that out it was too late. Maybe looking forward I could grep out links that contain the string beta or preview, but it's not like the current link has that string in it. Maybe I'll make a downgrade script.

**Comment by TapeWerm** [comment]
How to roll back from Minecraft Bedrock Edition 1.19.10 beta to 1.18.33:
```bash
sudo systemctl disable mcbe-getzip.timer mcbe-autoupdate@MCBE.service --now
sudo systemctl stop mcbe@MCBE
sudo su mc -s /bin/bash -c 'curl -L https://minecraft.azureedge.net/bin-linux/bedrock-server-1.18.33.02.zip -o ~/bedrock-server-1.18.33.02.zip'
sudo su mc -s /bin/bash -c '/opt/MCscripts/mcbe_update.sh ~/bedrock/MCBE ~/bedrock-server-1.18.33.02.zip'
# Replace BACKUP with pre update backup
sudo /opt/MCscripts/mcbe_restore.sh ~mc/bedrock/MCBE BACKUP
sudo systemctl start mcbe@MCBE
```

**Comment by joshhunt** [comment]
Thank you - I'm so glad we have TapeWorm!
