### ISSUE TITLE
Issue with EULA accepting

### ISSUE THREAD

**Issue by Salsbar** [TapeWerm/MCscripts#46]
Trying to set up MCBE with the setup script and I can't get passed the EULA accept.

root@minecraft:/opt# sudo /opt/MCscripts/mcbe_setup.sh --import /opt/MCBE MCBE
Enter Y if you agree to the Minecraft End User License Agreement and Privacy Policy
Minecraft End User License Agreement: https://minecraft.net/terms
Privacy Policy: https://go.microsoft.com/fwlink/?LinkId=521839
y
curl: (23) Failed writing body (0 != 6871)

**Comment by TapeWerm** [comment]
curl error is not from the EULA prompt. The EULA prompt is just me echo'ing the links Mojang asks you to read, and prompting you to enter Y. curl is a command that downloads the bedrock server webpage to get the download link, then curl is ran again on the download link. https://github.com/TapeWerm/MCscripts/blob/master/src/mcbe_getzip.sh is the script that does this. The EULA prompt is after curl'ing the bedrock server webpage for the download link, so it must be failing to curl the download link. curl writes the body to `~/"$current_ver".part` which is ran as user mc, so the parent directory is ~mc. I'm not sure why mcbe_getzip would fail writing to there.

**Comment by Salsbar** [comment]
It turned out to be an issue on my end. The mc user didn't have access to its home directory and the download would fail. Closing this issue, thanks.
