### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by afalzon** [TapeWerm/MCscripts#47]
Hi I am trying to understand how to use this set of scripts fully, I have MCBE running as a service which is running great! but how can i trigger it to run an update of Minecraft? I have some clients that have updated and can no longer connect to the server.
I found /opt/MCscripts/mcbe_autoupdate.sh but not 100% sure of the usage?
I also have ran `sudo systemctl enable mcbe-getzip.timer mcbe-autoupdate@MCBE.service --now`

**Comment by TapeWerm** [comment]
`sudo systemctl start mcbe-getzip.service` will run the bedrock getzip service. The bedrock autoupdate service should start after getzip runs. You probably ran into the bug I fixed a couple days ago in commit b5faac0b7eb76ee10c07dca81c754869d29c2730 . Try updating MCscripts if you haven't already. I might change the network test in ExecStartPre for the bedrock getzip and log services. It's a little janky, which is why it broke in the first place.

**Comment by afalzon** [comment]
thanks @TapeWerm I tried running `sudo systemctl start mcbe-getzip.service` but it just sat there with no response for hours. so i rebooted and ran the update commands:
`curl -L https://github.com/TapeWerm/MCscripts/archive/refs/heads/master.zip -o /tmp/master.zip`

`rm -rf /tmp/MCscripts-master`

`unzip /tmp/master.zip -d /tmp`

`sudo /tmp/MCscripts-master/src/install.sh`

the first 3 lines ran fine but then it just sits there with no response on the last one.

**Comment by TapeWerm** [comment]
By no response do you mean no output? If you read [install.sh source code](https://github.com/TapeWerm/MCscripts/blob/master/src/install.sh) you can see what it does. The install/update process installs required packages, adds the mc user, uninstalls MCscripts, moves servers and backups, installs MCscripts, and reenables services. Many steps output text to indicate progress. When install.sh uninstalls MCscripts, some services might not stop, and you have to wait for systemd to timeout and kill their processes.

`journalctl -u mcbe@MCBE.service -u mcbe-backup@MCBE.service -u mcbe-getzip.service -u mcbe-autoupdate@MCBE.service -u mcbe-log@MCBE -e` shows logs. If you post any logs, remember to delete gamertags from player connect/disconnect messages.

**Comment by afalzon** [comment]
Yeah, it had no output and just sits there like its doing something.

i have pasted my log here: [LOG File](https://pastebin.com/vrnEKdJQ)

Thanks For your help with this :)

**Comment by TapeWerm** [comment]
No output would imply that either you don't have apt-get, or apt-get is stuck. If you don't have apt-get, install.sh adds the mc user if it does not exist. Then disable_services.sh saves which services are enabled and disables them before deleting their files. It's pretty much an uninstaller.

`Nov 30 23:09:35 minecraft systemd[1]: mcbe-getzip.service: Current command vanished from the unit file, execution of the command list won't be resumed.` I've never seen that error before. At `Nov 30 23:09:24` the server stops and starts back up again. Is that when you tried to run install.sh? I use bash `set -e` to exit on error. So if it failed to stop mcbe-getzip and exited, it makes sense that the server would come back up again.

Thank you for the logs, I'm still not 100% sure why this happens, but I have some leads now.

**Comment by TapeWerm** [comment]
I run Ubuntu 22.04. I'm not using any systemd overrides. backup_dir is symlinked to a 2nd SSD formatted ext4. I don't think backup_dir has anything to do with this, but it has been important info for testing backup scripts. What is your server like? Is it up to date?

If you want to workaround this, you could try disabling the services by hand and enabling them after. That might work?

**Comment by afalzon** [comment]
Thanks, I just realised im running Ubuntu 18 on this one, I will try upgrading to 22 and see how it goes, i might even just blow it away and start fresh.

I am guessing the best method is:

1. Install Minecraft Server
2. Install your script by downloading it then running the install.sh

after that is it meant to keep minecraft updated as well?

If not what is the best method for updating Minecraft once your script is running?

**Comment by TapeWerm** [comment]
Sorry for the late reply. You might have to upgrade twice or do a clean install. https://ubuntu.com/server/docs/upgrade-introduction

Follow https://github.com/TapeWerm/MCscripts#setup and import your bedrock server directories. The getzip and autoupdate services automatically keep your server up to date.

**Comment by TapeWerm** [comment]
It's been a while, is your server still having issues? I had free time today so I figured I'd work on MCscripts. I have tomorrow off too.

**Comment by afalzon** [comment]
Sorry Vincent i havent had any luck with it but i am going to rebuild,
there is do many things on it that are not really good.

thanks for the follow up!

**Comment by TapeWerm** [comment]
Closing old issue, feel free to make a new one if anything happens.
