### ISSUE TITLE
Screen support?

### ISSUE THREAD

**Issue by 7dpk** [TapeWerm/MCscripts#51]
Hey! I know that using `screen` is not recommended cause of obvious reasons, but it happens that, I need to log into the server console and run some maintenance commands, also I've tried it running as service, but `systemd` seems to be troublesome, I'm using amazon-linux, I've created a script myself, but needed a robust solution, If you could extend the functionality a bit or guide me into the right direction, I'll be very grateful.

**Comment by TapeWerm** [comment]
MCscripts used to use tmux but in commit 02afc1627a945c8339dadf680088f494a1c880b3 I switched to systemd sockets for input and journalctl for output. Getting output after a timestamp or line in tmux is janky, I had to cut on input. In journalctl, you can get output after a timestamp or line ID'd by entry cursor. What are you having trouble with?

**Comment by 7dpk** [comment]
I'm having trouble with setting the backup script, currently I've a bedrock server running  on a spot ec2 instance, i.e. it may restart anytime usually 5-8 times in a month, so I tried writing a systemd script to start the server at system boot, and also restart it whenever the server crashes, which is very usual like every 3-4 days, I also need to interact with the server console to run some commands, e.g. whitelist, tell, kick etc., that's the reason I had to go with `screen` as using systemd didn't work in my case, it failed to start the service, So I used [this](https://dp7.me/snippets/startup-script-centOS) `init.d` method to run the script, as you can see from the link, now I had a very basic script setup for the backup which looks like this
```bash
#!/bin/bash

# Define variables
SCREEN_NAME="be"
BACKUP_DIR="/home/dpk/mc/backup"  # Replace with the actual backup directory on your server
S3_BUCKET_NAME="bedrock-test"

# Function to print logs/errors
print_log() {
    echo "[$(date +'%Y-%m-%d %H:%M:%S')] $1"
}

# Function to handle errors
handle_error() {
    print_log "Error: $1"
    # Add any necessary error handling code here
    # For example, you could send an email notification or perform other actions
    exit 1
}

# Enter the screen session and execute backup commands
print_log "Executing 'save hold' command..."
screen -S "$SCREEN_NAME" -p 0 -X stuff "save hold$(printf \\r)"
sleep 1  # Wait for the server to prepare for backup

print_log "Executing 'save query' command..."
screen -S "$SCREEN_NAME" -p 0 -X stuff "save query$(printf \\r)"
echo "Sleeping for 3 seconds to file be copied ... "
sleep 3
screen -S "$SCREEN_NAME" -p 0 -X hardcopy -h hardcopy.txt

# Wait for the backup to be ready
last_query_output=""
query_output=$(cat hardcopy.txt)
echo $query_output
if [[ $query_output == *"Data saved. Files are now ready to be copied."* ]]; then
    last_query_output="$query_output"
elif [[ $query_output == *"save query"* ]]; then
    break
fi

if [[ -z $last_query_output ]]; then
    handle_error "No 'save query' command output found."
fi

echo $last_query_output

# world="test/db/"
# files=$(echo "$last_query_output" | tr -d '\n' | grep -Eo -- "$world[^:]+:[0-9]+")

# temp_dir="$BACKUP_DIR/temp"
# backup_zip="$BACKUP_DIR/backup.zip"
# worlds_dir="/home/dpk/mc/worlds"

# mkdir -p "$temp_dir"
# cd "$temp_dir"
# rm -rf -- "$world"
# trap 'rm -f "$backup_zip"' ERR
# trap 'rm -rf -- "$world"; screen -S "$SCREEN_NAME" -p 0 -X stuff "save resume$(printf \\r)"' EXIT

# echo "$files" | while IFS='' read -r line; do
#     file=${line%:*}
#     dir=$(dirname -- "$file")
#     length=${line##*:}
#     mkdir -p -- "$dir"
#     cp -- "$worlds_dir/$file" "$dir/"
#     truncate --size="$length" -- "$file"
# done

# zip -rq "$backup_zip" -- "$worlds_dir"
# print_log "Backup is $backup_zip"

# # Upload the backup to S3
# print_log "Uploading backup to S3..."
# aws s3 cp "$backup_zip" "s3://$S3_BUCKET_NAME/" || handle_error "Failed to upload backup to S3"

# # Clean up temporary files
# print_log "Cleaning up temporary files..."
# rm "$backup_zip"
# rm -rf "$temp_dir"

# # Resume server changes
# print_log "Resuming server changes..."
# screen -S "$SCREEN_NAME" -p 0 -X stuff "save resume$(printf \\r)"

# print_log "Backup completed successfully."

``` 

and the below commented part is where I'm having issue with, I've tried to replicate your process but I'm stuck :(

**Comment by TapeWerm** [comment]
I haven't used AWS much, and I haven't used Amazon Linux. I've made some commits recently including today trying to reduce dependence on Debian, like e75167bc7cc04561841e2e55b5c45603920eff7. If you can install the packages I install with apt (or build from source), MCscripts might work. You should still be able to input to the server console via systemd sockets (like in [mc_cmd.sh](https://github.com/TapeWerm/MCscripts/blob/master/src/mc_cmd.sh)) and get output via journalctl.

Alma Linux 9:
```bash
dnf install -y curl dosfstools socat zip
dnf install -y python3-pip-wheel python3-requests python3-systemd
python3 -m pip install bs4 docker
```
I had to build https://www.w3.org/Tools/HTML-XML-utils/ from source, but when I transition to Python, that package won't be needed anymore. I started developing for Python 3.6 to support Ubuntu 18.04, but now I'm only testing on Python 3.8 to support Ubuntu 20.04. I'm not sure what minimum version of Bash is required for the Bash scripts.

**Comment by 7dpk** [comment]
Thank you so much, I've got so many ideas which might make it work now, although, I tried replicating the process on a ubuntu but, got some errors like "Got no socket", I guess I'll find some solution to it soon. I'm beginner to `systemd` and `sockets` if you could point me to some reference, it would nice.
